# Generated by Django 5.2.17 on 2026-09-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospital_accessrequest_doctor_doctor_pin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='responded_by',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='api.hospital')),
            ],
        ),
    ]
