# Generated by Django 6.1.1 on 2026-10-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_referral_responded_by_hospitalstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='encrypted_private_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='encryption_iv',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
