# Generated by Django 6.1.1 on 2026-10-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctor_encrypted_private_key_doctor_encryption_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
